{{- if and .Values.envSecret.create .Values.envSecret.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-e2e.labels" . | nindent 4 }}
stringData:
  {{- range $k, $v := .Values.envSecret.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
