/*
Copyright (C) 2012-2025 Tencent. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Machine{}, func(obj interface{}) { SetObjectDefaults_Machine(obj.(*Machine)) })
	scheme.AddTypeDefaultingFunc(&MachineList{}, func(obj interface{}) { SetObjectDefaults_MachineList(obj.(*MachineList)) })
	scheme.AddTypeDefaultingFunc(&MachineSet{}, func(obj interface{}) { SetObjectDefaults_MachineSet(obj.(*MachineSet)) })
	scheme.AddTypeDefaultingFunc(&MachineSetList{}, func(obj interface{}) { SetObjectDefaults_MachineSetList(obj.(*MachineSetList)) })
	scheme.AddTypeDefaultingFunc(&RollingUpgrade{}, func(obj interface{}) { SetObjectDefaults_RollingUpgrade(obj.(*RollingUpgrade)) })
	scheme.AddTypeDefaultingFunc(&RollingUpgradeList{}, func(obj interface{}) { SetObjectDefaults_RollingUpgradeList(obj.(*RollingUpgradeList)) })
	return nil
}

func SetObjectDefaults_Machine(in *Machine) {
	SetDefaults_Machine(in)
	SetDefaults_MachineSpec(&in.Spec)
	SetDefaults_ProviderSpec(&in.Spec.ProviderSpec)
}

func SetObjectDefaults_MachineList(in *MachineList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Machine(a)
	}
}

func SetObjectDefaults_MachineSet(in *MachineSet) {
	SetDefaults_MachineSet(in)
	SetDefaults_MachineSpec(&in.Spec.Template.Spec)
	SetDefaults_ProviderSpec(&in.Spec.Template.Spec.ProviderSpec)
}

func SetObjectDefaults_MachineSetList(in *MachineSetList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_MachineSet(a)
	}
}

func SetObjectDefaults_RollingUpgrade(in *RollingUpgrade) {
	SetDefaults_RollingUpgrade(in)
	SetDefaults_RollingUpgradeSpec(&in.Spec)
}

func SetObjectDefaults_RollingUpgradeList(in *RollingUpgradeList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_RollingUpgrade(a)
	}
}
