/*
Copyright (C) 2012-2025 Tencent. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	node "github.com/tencentcloud/karpenter-provider-tke/staging/nativenode"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	core "k8s.io/kubernetes/pkg/apis/core"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AutoUpgradeOptions)(nil), (*node.AutoUpgradeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AutoUpgradeOptions_To_node_AutoUpgradeOptions(a.(*AutoUpgradeOptions), b.(*node.AutoUpgradeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.AutoUpgradeOptions)(nil), (*AutoUpgradeOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_AutoUpgradeOptions_To_v1beta1_AutoUpgradeOptions(a.(*node.AutoUpgradeOptions), b.(*AutoUpgradeOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*node.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Condition_To_node_Condition(a.(*Condition), b.(*node.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_Condition_To_v1beta1_Condition(a.(*node.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GPUConfig)(nil), (*node.GPUConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GPUConfig_To_node_GPUConfig(a.(*GPUConfig), b.(*node.GPUConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.GPUConfig)(nil), (*GPUConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_GPUConfig_To_v1beta1_GPUConfig(a.(*node.GPUConfig), b.(*GPUConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GPUParams)(nil), (*node.GPUParams)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GPUParams_To_node_GPUParams(a.(*GPUParams), b.(*node.GPUParams), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.GPUParams)(nil), (*GPUParams)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_GPUParams_To_v1beta1_GPUParams(a.(*node.GPUParams), b.(*GPUParams), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LastOperation)(nil), (*node.LastOperation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LastOperation_To_node_LastOperation(a.(*LastOperation), b.(*node.LastOperation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.LastOperation)(nil), (*LastOperation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_LastOperation_To_v1beta1_LastOperation(a.(*node.LastOperation), b.(*LastOperation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LifecycleHook)(nil), (*node.LifecycleHook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LifecycleHook_To_node_LifecycleHook(a.(*LifecycleHook), b.(*node.LifecycleHook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.LifecycleHook)(nil), (*LifecycleHook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_LifecycleHook_To_v1beta1_LifecycleHook(a.(*node.LifecycleHook), b.(*LifecycleHook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachinSetScaling)(nil), (*node.MachinSetScaling)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachinSetScaling_To_node_MachinSetScaling(a.(*MachinSetScaling), b.(*node.MachinSetScaling), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachinSetScaling)(nil), (*MachinSetScaling)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachinSetScaling_To_v1beta1_MachinSetScaling(a.(*node.MachinSetScaling), b.(*MachinSetScaling), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Machine)(nil), (*node.Machine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Machine_To_node_Machine(a.(*Machine), b.(*node.Machine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.Machine)(nil), (*Machine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_Machine_To_v1beta1_Machine(a.(*node.Machine), b.(*Machine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineList)(nil), (*node.MachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineList_To_node_MachineList(a.(*MachineList), b.(*node.MachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineList)(nil), (*MachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineList_To_v1beta1_MachineList(a.(*node.MachineList), b.(*MachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineOperation)(nil), (*node.MachineOperation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineOperation_To_node_MachineOperation(a.(*MachineOperation), b.(*node.MachineOperation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineOperation)(nil), (*MachineOperation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineOperation_To_v1beta1_MachineOperation(a.(*node.MachineOperation), b.(*MachineOperation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineRollingUpdateStrategy)(nil), (*node.MachineRollingUpdateStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineRollingUpdateStrategy_To_node_MachineRollingUpdateStrategy(a.(*MachineRollingUpdateStrategy), b.(*node.MachineRollingUpdateStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineRollingUpdateStrategy)(nil), (*MachineRollingUpdateStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineRollingUpdateStrategy_To_v1beta1_MachineRollingUpdateStrategy(a.(*node.MachineRollingUpdateStrategy), b.(*MachineRollingUpdateStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSet)(nil), (*node.MachineSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineSet_To_node_MachineSet(a.(*MachineSet), b.(*node.MachineSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineSet)(nil), (*MachineSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineSet_To_v1beta1_MachineSet(a.(*node.MachineSet), b.(*MachineSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetCondition)(nil), (*node.MachineSetCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineSetCondition_To_node_MachineSetCondition(a.(*MachineSetCondition), b.(*node.MachineSetCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineSetCondition)(nil), (*MachineSetCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineSetCondition_To_v1beta1_MachineSetCondition(a.(*node.MachineSetCondition), b.(*MachineSetCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetList)(nil), (*node.MachineSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineSetList_To_node_MachineSetList(a.(*MachineSetList), b.(*node.MachineSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineSetList)(nil), (*MachineSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineSetList_To_v1beta1_MachineSetList(a.(*node.MachineSetList), b.(*MachineSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetSpec)(nil), (*node.MachineSetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineSetSpec_To_node_MachineSetSpec(a.(*MachineSetSpec), b.(*node.MachineSetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineSetSpec)(nil), (*MachineSetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineSetSpec_To_v1beta1_MachineSetSpec(a.(*node.MachineSetSpec), b.(*MachineSetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetStatus)(nil), (*node.MachineSetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineSetStatus_To_node_MachineSetStatus(a.(*MachineSetStatus), b.(*node.MachineSetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineSetStatus)(nil), (*MachineSetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineSetStatus_To_v1beta1_MachineSetStatus(a.(*node.MachineSetStatus), b.(*MachineSetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSpec)(nil), (*node.MachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineSpec_To_node_MachineSpec(a.(*MachineSpec), b.(*node.MachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineSpec)(nil), (*MachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineSpec_To_v1beta1_MachineSpec(a.(*node.MachineSpec), b.(*MachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineStatus)(nil), (*node.MachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineStatus_To_node_MachineStatus(a.(*MachineStatus), b.(*node.MachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineStatus)(nil), (*MachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineStatus_To_v1beta1_MachineStatus(a.(*node.MachineStatus), b.(*MachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineTemplateSpec)(nil), (*node.MachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineTemplateSpec_To_node_MachineTemplateSpec(a.(*MachineTemplateSpec), b.(*node.MachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineTemplateSpec)(nil), (*MachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineTemplateSpec_To_v1beta1_MachineTemplateSpec(a.(*node.MachineTemplateSpec), b.(*MachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineUpdateStrategy)(nil), (*node.MachineUpdateStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineUpdateStrategy_To_node_MachineUpdateStrategy(a.(*MachineUpdateStrategy), b.(*node.MachineUpdateStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MachineUpdateStrategy)(nil), (*MachineUpdateStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MachineUpdateStrategy_To_v1beta1_MachineUpdateStrategy(a.(*node.MachineUpdateStrategy), b.(*MachineUpdateStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeReference)(nil), (*node.NodeReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NodeReference_To_node_NodeReference(a.(*NodeReference), b.(*node.NodeReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.NodeReference)(nil), (*NodeReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_NodeReference_To_v1beta1_NodeReference(a.(*node.NodeReference), b.(*NodeReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectMeta)(nil), (*node.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ObjectMeta_To_node_ObjectMeta(a.(*ObjectMeta), b.(*node.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.ObjectMeta)(nil), (*ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_ObjectMeta_To_v1beta1_ObjectMeta(a.(*node.ObjectMeta), b.(*ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProviderSpec)(nil), (*node.ProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ProviderSpec_To_node_ProviderSpec(a.(*ProviderSpec), b.(*node.ProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.ProviderSpec)(nil), (*ProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_ProviderSpec_To_v1beta1_ProviderSpec(a.(*node.ProviderSpec), b.(*ProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RollingUpgrade)(nil), (*node.RollingUpgrade)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RollingUpgrade_To_node_RollingUpgrade(a.(*RollingUpgrade), b.(*node.RollingUpgrade), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.RollingUpgrade)(nil), (*RollingUpgrade)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_RollingUpgrade_To_v1beta1_RollingUpgrade(a.(*node.RollingUpgrade), b.(*RollingUpgrade), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RollingUpgradeCondition)(nil), (*node.RollingUpgradeCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RollingUpgradeCondition_To_node_RollingUpgradeCondition(a.(*RollingUpgradeCondition), b.(*node.RollingUpgradeCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.RollingUpgradeCondition)(nil), (*RollingUpgradeCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_RollingUpgradeCondition_To_v1beta1_RollingUpgradeCondition(a.(*node.RollingUpgradeCondition), b.(*RollingUpgradeCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RollingUpgradeList)(nil), (*node.RollingUpgradeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RollingUpgradeList_To_node_RollingUpgradeList(a.(*RollingUpgradeList), b.(*node.RollingUpgradeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.RollingUpgradeList)(nil), (*RollingUpgradeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_RollingUpgradeList_To_v1beta1_RollingUpgradeList(a.(*node.RollingUpgradeList), b.(*RollingUpgradeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RollingUpgradeSpec)(nil), (*node.RollingUpgradeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RollingUpgradeSpec_To_node_RollingUpgradeSpec(a.(*RollingUpgradeSpec), b.(*node.RollingUpgradeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.RollingUpgradeSpec)(nil), (*RollingUpgradeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_RollingUpgradeSpec_To_v1beta1_RollingUpgradeSpec(a.(*node.RollingUpgradeSpec), b.(*RollingUpgradeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RollingUpgradeStatus)(nil), (*node.RollingUpgradeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RollingUpgradeStatus_To_node_RollingUpgradeStatus(a.(*RollingUpgradeStatus), b.(*node.RollingUpgradeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.RollingUpgradeStatus)(nil), (*RollingUpgradeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_RollingUpgradeStatus_To_v1beta1_RollingUpgradeStatus(a.(*node.RollingUpgradeStatus), b.(*RollingUpgradeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TagSpecification)(nil), (*node.TagSpecification)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TagSpecification_To_node_TagSpecification(a.(*TagSpecification), b.(*node.TagSpecification), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.TagSpecification)(nil), (*TagSpecification)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_TagSpecification_To_v1beta1_TagSpecification(a.(*node.TagSpecification), b.(*TagSpecification), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpdateStrategy)(nil), (*node.UpdateStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UpdateStrategy_To_node_UpdateStrategy(a.(*UpdateStrategy), b.(*node.UpdateStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.UpdateStrategy)(nil), (*UpdateStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_UpdateStrategy_To_v1beta1_UpdateStrategy(a.(*node.UpdateStrategy), b.(*UpdateStrategy), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_AutoUpgradeOptions_To_node_AutoUpgradeOptions(in *AutoUpgradeOptions, out *node.AutoUpgradeOptions, s conversion.Scope) error {
	out.AutoUpgradeStartTime = in.AutoUpgradeStartTime
	out.Duration = in.Duration
	out.WeeklyPeriod = *(*[]string)(unsafe.Pointer(&in.WeeklyPeriod))
	return nil
}

// Convert_v1beta1_AutoUpgradeOptions_To_node_AutoUpgradeOptions is an autogenerated conversion function.
func Convert_v1beta1_AutoUpgradeOptions_To_node_AutoUpgradeOptions(in *AutoUpgradeOptions, out *node.AutoUpgradeOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_AutoUpgradeOptions_To_node_AutoUpgradeOptions(in, out, s)
}

func autoConvert_node_AutoUpgradeOptions_To_v1beta1_AutoUpgradeOptions(in *node.AutoUpgradeOptions, out *AutoUpgradeOptions, s conversion.Scope) error {
	out.AutoUpgradeStartTime = in.AutoUpgradeStartTime
	out.Duration = in.Duration
	out.WeeklyPeriod = *(*[]string)(unsafe.Pointer(&in.WeeklyPeriod))
	return nil
}

// Convert_node_AutoUpgradeOptions_To_v1beta1_AutoUpgradeOptions is an autogenerated conversion function.
func Convert_node_AutoUpgradeOptions_To_v1beta1_AutoUpgradeOptions(in *node.AutoUpgradeOptions, out *AutoUpgradeOptions, s conversion.Scope) error {
	return autoConvert_node_AutoUpgradeOptions_To_v1beta1_AutoUpgradeOptions(in, out, s)
}

func autoConvert_v1beta1_Condition_To_node_Condition(in *Condition, out *node.Condition, s conversion.Scope) error {
	out.Type = node.ConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.Severity = node.ConditionSeverity(in.Severity)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1beta1_Condition_To_node_Condition is an autogenerated conversion function.
func Convert_v1beta1_Condition_To_node_Condition(in *Condition, out *node.Condition, s conversion.Scope) error {
	return autoConvert_v1beta1_Condition_To_node_Condition(in, out, s)
}

func autoConvert_node_Condition_To_v1beta1_Condition(in *node.Condition, out *Condition, s conversion.Scope) error {
	out.Type = ConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.Severity = ConditionSeverity(in.Severity)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_node_Condition_To_v1beta1_Condition is an autogenerated conversion function.
func Convert_node_Condition_To_v1beta1_Condition(in *node.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_node_Condition_To_v1beta1_Condition(in, out, s)
}

func autoConvert_v1beta1_GPUConfig_To_node_GPUConfig(in *GPUConfig, out *node.GPUConfig, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	out.Driver = in.Driver
	out.CUDA = in.CUDA
	out.CUDNN = in.CUDNN
	out.MIGEnable = in.MIGEnable
	out.Fabric = in.Fabric
	return nil
}

// Convert_v1beta1_GPUConfig_To_node_GPUConfig is an autogenerated conversion function.
func Convert_v1beta1_GPUConfig_To_node_GPUConfig(in *GPUConfig, out *node.GPUConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_GPUConfig_To_node_GPUConfig(in, out, s)
}

func autoConvert_node_GPUConfig_To_v1beta1_GPUConfig(in *node.GPUConfig, out *GPUConfig, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	out.Driver = in.Driver
	out.CUDA = in.CUDA
	out.CUDNN = in.CUDNN
	out.MIGEnable = in.MIGEnable
	out.Fabric = in.Fabric
	return nil
}

// Convert_node_GPUConfig_To_v1beta1_GPUConfig is an autogenerated conversion function.
func Convert_node_GPUConfig_To_v1beta1_GPUConfig(in *node.GPUConfig, out *GPUConfig, s conversion.Scope) error {
	return autoConvert_node_GPUConfig_To_v1beta1_GPUConfig(in, out, s)
}

func autoConvert_v1beta1_GPUParams_To_node_GPUParams(in *GPUParams, out *node.GPUParams, s conversion.Scope) error {
	out.Driver = in.Driver
	out.CUDA = in.CUDA
	out.CUDNN = in.CUDNN
	out.MIGEnable = in.MIGEnable
	out.Fabric = in.Fabric
	return nil
}

// Convert_v1beta1_GPUParams_To_node_GPUParams is an autogenerated conversion function.
func Convert_v1beta1_GPUParams_To_node_GPUParams(in *GPUParams, out *node.GPUParams, s conversion.Scope) error {
	return autoConvert_v1beta1_GPUParams_To_node_GPUParams(in, out, s)
}

func autoConvert_node_GPUParams_To_v1beta1_GPUParams(in *node.GPUParams, out *GPUParams, s conversion.Scope) error {
	out.Driver = in.Driver
	out.CUDA = in.CUDA
	out.CUDNN = in.CUDNN
	out.MIGEnable = in.MIGEnable
	out.Fabric = in.Fabric
	return nil
}

// Convert_node_GPUParams_To_v1beta1_GPUParams is an autogenerated conversion function.
func Convert_node_GPUParams_To_v1beta1_GPUParams(in *node.GPUParams, out *GPUParams, s conversion.Scope) error {
	return autoConvert_node_GPUParams_To_v1beta1_GPUParams(in, out, s)
}

func autoConvert_v1beta1_LastOperation_To_node_LastOperation(in *LastOperation, out *node.LastOperation, s conversion.Scope) error {
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	out.State = (*string)(unsafe.Pointer(in.State))
	out.Type = (*string)(unsafe.Pointer(in.Type))
	return nil
}

// Convert_v1beta1_LastOperation_To_node_LastOperation is an autogenerated conversion function.
func Convert_v1beta1_LastOperation_To_node_LastOperation(in *LastOperation, out *node.LastOperation, s conversion.Scope) error {
	return autoConvert_v1beta1_LastOperation_To_node_LastOperation(in, out, s)
}

func autoConvert_node_LastOperation_To_v1beta1_LastOperation(in *node.LastOperation, out *LastOperation, s conversion.Scope) error {
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	out.State = (*string)(unsafe.Pointer(in.State))
	out.Type = (*string)(unsafe.Pointer(in.Type))
	return nil
}

// Convert_node_LastOperation_To_v1beta1_LastOperation is an autogenerated conversion function.
func Convert_node_LastOperation_To_v1beta1_LastOperation(in *node.LastOperation, out *LastOperation, s conversion.Scope) error {
	return autoConvert_node_LastOperation_To_v1beta1_LastOperation(in, out, s)
}

func autoConvert_v1beta1_LifecycleHook_To_node_LifecycleHook(in *LifecycleHook, out *node.LifecycleHook, s conversion.Scope) error {
	out.Name = in.Name
	out.Owner = in.Owner
	return nil
}

// Convert_v1beta1_LifecycleHook_To_node_LifecycleHook is an autogenerated conversion function.
func Convert_v1beta1_LifecycleHook_To_node_LifecycleHook(in *LifecycleHook, out *node.LifecycleHook, s conversion.Scope) error {
	return autoConvert_v1beta1_LifecycleHook_To_node_LifecycleHook(in, out, s)
}

func autoConvert_node_LifecycleHook_To_v1beta1_LifecycleHook(in *node.LifecycleHook, out *LifecycleHook, s conversion.Scope) error {
	out.Name = in.Name
	out.Owner = in.Owner
	return nil
}

// Convert_node_LifecycleHook_To_v1beta1_LifecycleHook is an autogenerated conversion function.
func Convert_node_LifecycleHook_To_v1beta1_LifecycleHook(in *node.LifecycleHook, out *LifecycleHook, s conversion.Scope) error {
	return autoConvert_node_LifecycleHook_To_v1beta1_LifecycleHook(in, out, s)
}

func autoConvert_v1beta1_MachinSetScaling_To_node_MachinSetScaling(in *MachinSetScaling, out *node.MachinSetScaling, s conversion.Scope) error {
	out.MinReplicas = in.MinReplicas
	out.MaxReplicas = in.MaxReplicas
	out.CreatePolicy = (*node.MachineCreatePolicy)(unsafe.Pointer(in.CreatePolicy))
	return nil
}

// Convert_v1beta1_MachinSetScaling_To_node_MachinSetScaling is an autogenerated conversion function.
func Convert_v1beta1_MachinSetScaling_To_node_MachinSetScaling(in *MachinSetScaling, out *node.MachinSetScaling, s conversion.Scope) error {
	return autoConvert_v1beta1_MachinSetScaling_To_node_MachinSetScaling(in, out, s)
}

func autoConvert_node_MachinSetScaling_To_v1beta1_MachinSetScaling(in *node.MachinSetScaling, out *MachinSetScaling, s conversion.Scope) error {
	out.MinReplicas = in.MinReplicas
	out.MaxReplicas = in.MaxReplicas
	out.CreatePolicy = (*MachineCreatePolicy)(unsafe.Pointer(in.CreatePolicy))
	return nil
}

// Convert_node_MachinSetScaling_To_v1beta1_MachinSetScaling is an autogenerated conversion function.
func Convert_node_MachinSetScaling_To_v1beta1_MachinSetScaling(in *node.MachinSetScaling, out *MachinSetScaling, s conversion.Scope) error {
	return autoConvert_node_MachinSetScaling_To_v1beta1_MachinSetScaling(in, out, s)
}

func autoConvert_v1beta1_Machine_To_node_Machine(in *Machine, out *node.Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_MachineSpec_To_node_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_MachineStatus_To_node_MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Machine_To_node_Machine is an autogenerated conversion function.
func Convert_v1beta1_Machine_To_node_Machine(in *Machine, out *node.Machine, s conversion.Scope) error {
	return autoConvert_v1beta1_Machine_To_node_Machine(in, out, s)
}

func autoConvert_node_Machine_To_v1beta1_Machine(in *node.Machine, out *Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_MachineSpec_To_v1beta1_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_MachineStatus_To_v1beta1_MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_Machine_To_v1beta1_Machine is an autogenerated conversion function.
func Convert_node_Machine_To_v1beta1_Machine(in *node.Machine, out *Machine, s conversion.Scope) error {
	return autoConvert_node_Machine_To_v1beta1_Machine(in, out, s)
}

func autoConvert_v1beta1_MachineList_To_node_MachineList(in *MachineList, out *node.MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_MachineList_To_node_MachineList is an autogenerated conversion function.
func Convert_v1beta1_MachineList_To_node_MachineList(in *MachineList, out *node.MachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineList_To_node_MachineList(in, out, s)
}

func autoConvert_node_MachineList_To_v1beta1_MachineList(in *node.MachineList, out *MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_MachineList_To_v1beta1_MachineList is an autogenerated conversion function.
func Convert_node_MachineList_To_v1beta1_MachineList(in *node.MachineList, out *MachineList, s conversion.Scope) error {
	return autoConvert_node_MachineList_To_v1beta1_MachineList(in, out, s)
}

func autoConvert_v1beta1_MachineOperation_To_node_MachineOperation(in *MachineOperation, out *node.MachineOperation, s conversion.Scope) error {
	out.Action = node.OperationAction(in.Action)
	out.StopType = node.StopType(in.StopType)
	return nil
}

// Convert_v1beta1_MachineOperation_To_node_MachineOperation is an autogenerated conversion function.
func Convert_v1beta1_MachineOperation_To_node_MachineOperation(in *MachineOperation, out *node.MachineOperation, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineOperation_To_node_MachineOperation(in, out, s)
}

func autoConvert_node_MachineOperation_To_v1beta1_MachineOperation(in *node.MachineOperation, out *MachineOperation, s conversion.Scope) error {
	out.Action = OperationAction(in.Action)
	out.StopType = StopType(in.StopType)
	return nil
}

// Convert_node_MachineOperation_To_v1beta1_MachineOperation is an autogenerated conversion function.
func Convert_node_MachineOperation_To_v1beta1_MachineOperation(in *node.MachineOperation, out *MachineOperation, s conversion.Scope) error {
	return autoConvert_node_MachineOperation_To_v1beta1_MachineOperation(in, out, s)
}

func autoConvert_v1beta1_MachineRollingUpdateStrategy_To_node_MachineRollingUpdateStrategy(in *MachineRollingUpdateStrategy, out *node.MachineRollingUpdateStrategy, s conversion.Scope) error {
	out.MaxConfigUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxConfigUnavailable))
	out.MaxSteps = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSteps))
	return nil
}

// Convert_v1beta1_MachineRollingUpdateStrategy_To_node_MachineRollingUpdateStrategy is an autogenerated conversion function.
func Convert_v1beta1_MachineRollingUpdateStrategy_To_node_MachineRollingUpdateStrategy(in *MachineRollingUpdateStrategy, out *node.MachineRollingUpdateStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineRollingUpdateStrategy_To_node_MachineRollingUpdateStrategy(in, out, s)
}

func autoConvert_node_MachineRollingUpdateStrategy_To_v1beta1_MachineRollingUpdateStrategy(in *node.MachineRollingUpdateStrategy, out *MachineRollingUpdateStrategy, s conversion.Scope) error {
	out.MaxConfigUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxConfigUnavailable))
	out.MaxSteps = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSteps))
	return nil
}

// Convert_node_MachineRollingUpdateStrategy_To_v1beta1_MachineRollingUpdateStrategy is an autogenerated conversion function.
func Convert_node_MachineRollingUpdateStrategy_To_v1beta1_MachineRollingUpdateStrategy(in *node.MachineRollingUpdateStrategy, out *MachineRollingUpdateStrategy, s conversion.Scope) error {
	return autoConvert_node_MachineRollingUpdateStrategy_To_v1beta1_MachineRollingUpdateStrategy(in, out, s)
}

func autoConvert_v1beta1_MachineSet_To_node_MachineSet(in *MachineSet, out *node.MachineSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_MachineSetSpec_To_node_MachineSetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_MachineSetStatus_To_node_MachineSetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MachineSet_To_node_MachineSet is an autogenerated conversion function.
func Convert_v1beta1_MachineSet_To_node_MachineSet(in *MachineSet, out *node.MachineSet, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineSet_To_node_MachineSet(in, out, s)
}

func autoConvert_node_MachineSet_To_v1beta1_MachineSet(in *node.MachineSet, out *MachineSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_MachineSetSpec_To_v1beta1_MachineSetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_MachineSetStatus_To_v1beta1_MachineSetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_MachineSet_To_v1beta1_MachineSet is an autogenerated conversion function.
func Convert_node_MachineSet_To_v1beta1_MachineSet(in *node.MachineSet, out *MachineSet, s conversion.Scope) error {
	return autoConvert_node_MachineSet_To_v1beta1_MachineSet(in, out, s)
}

func autoConvert_v1beta1_MachineSetCondition_To_node_MachineSetCondition(in *MachineSetCondition, out *node.MachineSetCondition, s conversion.Scope) error {
	out.Type = node.MachineSetConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1beta1_MachineSetCondition_To_node_MachineSetCondition is an autogenerated conversion function.
func Convert_v1beta1_MachineSetCondition_To_node_MachineSetCondition(in *MachineSetCondition, out *node.MachineSetCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineSetCondition_To_node_MachineSetCondition(in, out, s)
}

func autoConvert_node_MachineSetCondition_To_v1beta1_MachineSetCondition(in *node.MachineSetCondition, out *MachineSetCondition, s conversion.Scope) error {
	out.Type = MachineSetConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_node_MachineSetCondition_To_v1beta1_MachineSetCondition is an autogenerated conversion function.
func Convert_node_MachineSetCondition_To_v1beta1_MachineSetCondition(in *node.MachineSetCondition, out *MachineSetCondition, s conversion.Scope) error {
	return autoConvert_node_MachineSetCondition_To_v1beta1_MachineSetCondition(in, out, s)
}

func autoConvert_v1beta1_MachineSetList_To_node_MachineSetList(in *MachineSetList, out *node.MachineSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.MachineSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_MachineSetList_To_node_MachineSetList is an autogenerated conversion function.
func Convert_v1beta1_MachineSetList_To_node_MachineSetList(in *MachineSetList, out *node.MachineSetList, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineSetList_To_node_MachineSetList(in, out, s)
}

func autoConvert_node_MachineSetList_To_v1beta1_MachineSetList(in *node.MachineSetList, out *MachineSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MachineSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_MachineSetList_To_v1beta1_MachineSetList is an autogenerated conversion function.
func Convert_node_MachineSetList_To_v1beta1_MachineSetList(in *node.MachineSetList, out *MachineSetList, s conversion.Scope) error {
	return autoConvert_node_MachineSetList_To_v1beta1_MachineSetList(in, out, s)
}

func autoConvert_v1beta1_MachineSetSpec_To_node_MachineSetSpec(in *MachineSetSpec, out *node.MachineSetSpec, s conversion.Scope) error {
	out.Type = node.MachineSetType(in.Type)
	out.DisplayName = in.DisplayName
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	if err := Convert_v1beta1_MachineTemplateSpec_To_node_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	out.HealthCheckPolicyName = (*string)(unsafe.Pointer(in.HealthCheckPolicyName))
	out.MinReadySeconds = in.MinReadySeconds
	out.DeletePolicy = node.MachineSetDeletePolicy(in.DeletePolicy)
	out.SubnetIDs = *(*[]string)(unsafe.Pointer(&in.SubnetIDs))
	out.InstanceTypes = *(*[]string)(unsafe.Pointer(&in.InstanceTypes))
	if err := Convert_v1beta1_MachinSetScaling_To_node_MachinSetScaling(&in.Scaling, &out.Scaling, s); err != nil {
		return err
	}
	out.AutoRepair = (*bool)(unsafe.Pointer(in.AutoRepair))
	out.GPUConfigs = *(*[]node.GPUConfig)(unsafe.Pointer(&in.GPUConfigs))
	out.KeyID = in.KeyID
	if err := Convert_v1beta1_MachineUpdateStrategy_To_node_MachineUpdateStrategy(&in.MachineUpdateStrategy, &out.MachineUpdateStrategy, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MachineSetSpec_To_node_MachineSetSpec is an autogenerated conversion function.
func Convert_v1beta1_MachineSetSpec_To_node_MachineSetSpec(in *MachineSetSpec, out *node.MachineSetSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineSetSpec_To_node_MachineSetSpec(in, out, s)
}

func autoConvert_node_MachineSetSpec_To_v1beta1_MachineSetSpec(in *node.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	out.Type = MachineSetType(in.Type)
	out.DisplayName = in.DisplayName
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	if err := Convert_node_MachineTemplateSpec_To_v1beta1_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	out.HealthCheckPolicyName = (*string)(unsafe.Pointer(in.HealthCheckPolicyName))
	out.MinReadySeconds = in.MinReadySeconds
	out.DeletePolicy = MachineSetDeletePolicy(in.DeletePolicy)
	out.SubnetIDs = *(*[]string)(unsafe.Pointer(&in.SubnetIDs))
	out.InstanceTypes = *(*[]string)(unsafe.Pointer(&in.InstanceTypes))
	if err := Convert_node_MachinSetScaling_To_v1beta1_MachinSetScaling(&in.Scaling, &out.Scaling, s); err != nil {
		return err
	}
	out.AutoRepair = (*bool)(unsafe.Pointer(in.AutoRepair))
	out.GPUConfigs = *(*[]GPUConfig)(unsafe.Pointer(&in.GPUConfigs))
	out.KeyID = in.KeyID
	if err := Convert_node_MachineUpdateStrategy_To_v1beta1_MachineUpdateStrategy(&in.MachineUpdateStrategy, &out.MachineUpdateStrategy, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_MachineSetSpec_To_v1beta1_MachineSetSpec is an autogenerated conversion function.
func Convert_node_MachineSetSpec_To_v1beta1_MachineSetSpec(in *node.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	return autoConvert_node_MachineSetSpec_To_v1beta1_MachineSetSpec(in, out, s)
}

func autoConvert_v1beta1_MachineSetStatus_To_node_MachineSetStatus(in *MachineSetStatus, out *node.MachineSetStatus, s conversion.Scope) error {
	out.HealthCheckPolicyRevision = (*string)(unsafe.Pointer(in.HealthCheckPolicyRevision))
	out.Replicas = in.Replicas
	out.FullyLabeledReplicas = in.FullyLabeledReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.ObservedGeneration = in.ObservedGeneration
	out.KubeletVersion = in.KubeletVersion
	out.RuntimeVersion = in.RuntimeVersion
	out.Conditions = *(*[]node.MachineSetCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_MachineSetStatus_To_node_MachineSetStatus is an autogenerated conversion function.
func Convert_v1beta1_MachineSetStatus_To_node_MachineSetStatus(in *MachineSetStatus, out *node.MachineSetStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineSetStatus_To_node_MachineSetStatus(in, out, s)
}

func autoConvert_node_MachineSetStatus_To_v1beta1_MachineSetStatus(in *node.MachineSetStatus, out *MachineSetStatus, s conversion.Scope) error {
	out.HealthCheckPolicyRevision = (*string)(unsafe.Pointer(in.HealthCheckPolicyRevision))
	out.Replicas = in.Replicas
	out.FullyLabeledReplicas = in.FullyLabeledReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.ObservedGeneration = in.ObservedGeneration
	out.KubeletVersion = in.KubeletVersion
	out.RuntimeVersion = in.RuntimeVersion
	out.Conditions = *(*[]MachineSetCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_node_MachineSetStatus_To_v1beta1_MachineSetStatus is an autogenerated conversion function.
func Convert_node_MachineSetStatus_To_v1beta1_MachineSetStatus(in *node.MachineSetStatus, out *MachineSetStatus, s conversion.Scope) error {
	return autoConvert_node_MachineSetStatus_To_v1beta1_MachineSetStatus(in, out, s)
}

func autoConvert_v1beta1_MachineSpec_To_node_MachineSpec(in *MachineSpec, out *node.MachineSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_ObjectMeta_To_node_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	out.DisplayName = in.DisplayName
	out.Zone = in.Zone
	out.SubnetID = in.SubnetID
	out.Taints = *(*[]core.Taint)(unsafe.Pointer(&in.Taints))
	out.RuntimeRootDir = in.RuntimeRootDir
	out.KubeletVersion = (*string)(unsafe.Pointer(in.KubeletVersion))
	out.RuntimeVersion = (*string)(unsafe.Pointer(in.RuntimeVersion))
	if err := Convert_v1beta1_GPUParams_To_node_GPUParams(&in.GPUConfig, &out.GPUConfig, s); err != nil {
		return err
	}
	out.Unschedulable = in.Unschedulable
	if err := Convert_v1beta1_ProviderSpec_To_node_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	return nil
}

// Convert_v1beta1_MachineSpec_To_node_MachineSpec is an autogenerated conversion function.
func Convert_v1beta1_MachineSpec_To_node_MachineSpec(in *MachineSpec, out *node.MachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineSpec_To_node_MachineSpec(in, out, s)
}

func autoConvert_node_MachineSpec_To_v1beta1_MachineSpec(in *node.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	if err := Convert_node_ObjectMeta_To_v1beta1_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	out.DisplayName = in.DisplayName
	out.Zone = in.Zone
	out.SubnetID = in.SubnetID
	out.Taints = *(*[]corev1.Taint)(unsafe.Pointer(&in.Taints))
	out.RuntimeRootDir = in.RuntimeRootDir
	out.KubeletVersion = (*string)(unsafe.Pointer(in.KubeletVersion))
	out.RuntimeVersion = (*string)(unsafe.Pointer(in.RuntimeVersion))
	if err := Convert_node_GPUParams_To_v1beta1_GPUParams(&in.GPUConfig, &out.GPUConfig, s); err != nil {
		return err
	}
	out.Unschedulable = in.Unschedulable
	if err := Convert_node_ProviderSpec_To_v1beta1_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	return nil
}

// Convert_node_MachineSpec_To_v1beta1_MachineSpec is an autogenerated conversion function.
func Convert_node_MachineSpec_To_v1beta1_MachineSpec(in *node.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	return autoConvert_node_MachineSpec_To_v1beta1_MachineSpec(in, out, s)
}

func autoConvert_v1beta1_MachineStatus_To_node_MachineStatus(in *MachineStatus, out *node.MachineStatus, s conversion.Scope) error {
	out.NodeRef = (*node.NodeReference)(unsafe.Pointer(in.NodeRef))
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	out.FailureReason = (*node.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.ProviderStatus = (*runtime.RawExtension)(unsafe.Pointer(in.ProviderStatus))
	out.Addresses = *(*[]core.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.LastOperation = (*node.LastOperation)(unsafe.Pointer(in.LastOperation))
	out.Phase = (*string)(unsafe.Pointer(in.Phase))
	out.Conditions = *(*[]node.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_MachineStatus_To_node_MachineStatus is an autogenerated conversion function.
func Convert_v1beta1_MachineStatus_To_node_MachineStatus(in *MachineStatus, out *node.MachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineStatus_To_node_MachineStatus(in, out, s)
}

func autoConvert_node_MachineStatus_To_v1beta1_MachineStatus(in *node.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	out.NodeRef = (*NodeReference)(unsafe.Pointer(in.NodeRef))
	out.LastUpdated = (*v1.Time)(unsafe.Pointer(in.LastUpdated))
	out.FailureReason = (*MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.ProviderStatus = (*runtime.RawExtension)(unsafe.Pointer(in.ProviderStatus))
	out.Addresses = *(*[]corev1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.LastOperation = (*LastOperation)(unsafe.Pointer(in.LastOperation))
	out.Phase = (*string)(unsafe.Pointer(in.Phase))
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_node_MachineStatus_To_v1beta1_MachineStatus is an autogenerated conversion function.
func Convert_node_MachineStatus_To_v1beta1_MachineStatus(in *node.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	return autoConvert_node_MachineStatus_To_v1beta1_MachineStatus(in, out, s)
}

func autoConvert_v1beta1_MachineTemplateSpec_To_node_MachineTemplateSpec(in *MachineTemplateSpec, out *node.MachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_ObjectMeta_To_node_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_MachineSpec_To_node_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MachineTemplateSpec_To_node_MachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_MachineTemplateSpec_To_node_MachineTemplateSpec(in *MachineTemplateSpec, out *node.MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineTemplateSpec_To_node_MachineTemplateSpec(in, out, s)
}

func autoConvert_node_MachineTemplateSpec_To_v1beta1_MachineTemplateSpec(in *node.MachineTemplateSpec, out *MachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_node_ObjectMeta_To_v1beta1_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_node_MachineSpec_To_v1beta1_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_MachineTemplateSpec_To_v1beta1_MachineTemplateSpec is an autogenerated conversion function.
func Convert_node_MachineTemplateSpec_To_v1beta1_MachineTemplateSpec(in *node.MachineTemplateSpec, out *MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_node_MachineTemplateSpec_To_v1beta1_MachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_MachineUpdateStrategy_To_node_MachineUpdateStrategy(in *MachineUpdateStrategy, out *node.MachineUpdateStrategy, s conversion.Scope) error {
	out.Type = node.MachineUpdateStrategyType(in.Type)
	out.RollingUpdate = (*node.MachineRollingUpdateStrategy)(unsafe.Pointer(in.RollingUpdate))
	return nil
}

// Convert_v1beta1_MachineUpdateStrategy_To_node_MachineUpdateStrategy is an autogenerated conversion function.
func Convert_v1beta1_MachineUpdateStrategy_To_node_MachineUpdateStrategy(in *MachineUpdateStrategy, out *node.MachineUpdateStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineUpdateStrategy_To_node_MachineUpdateStrategy(in, out, s)
}

func autoConvert_node_MachineUpdateStrategy_To_v1beta1_MachineUpdateStrategy(in *node.MachineUpdateStrategy, out *MachineUpdateStrategy, s conversion.Scope) error {
	out.Type = MachineUpdateStrategyType(in.Type)
	out.RollingUpdate = (*MachineRollingUpdateStrategy)(unsafe.Pointer(in.RollingUpdate))
	return nil
}

// Convert_node_MachineUpdateStrategy_To_v1beta1_MachineUpdateStrategy is an autogenerated conversion function.
func Convert_node_MachineUpdateStrategy_To_v1beta1_MachineUpdateStrategy(in *node.MachineUpdateStrategy, out *MachineUpdateStrategy, s conversion.Scope) error {
	return autoConvert_node_MachineUpdateStrategy_To_v1beta1_MachineUpdateStrategy(in, out, s)
}

func autoConvert_v1beta1_NodeReference_To_node_NodeReference(in *NodeReference, out *node.NodeReference, s conversion.Scope) error {
	out.Name = in.Name
	out.OSImage = in.OSImage
	out.Architecture = in.Architecture
	out.KubeletVersion = in.KubeletVersion
	out.RuntimeVersion = in.RuntimeVersion
	return nil
}

// Convert_v1beta1_NodeReference_To_node_NodeReference is an autogenerated conversion function.
func Convert_v1beta1_NodeReference_To_node_NodeReference(in *NodeReference, out *node.NodeReference, s conversion.Scope) error {
	return autoConvert_v1beta1_NodeReference_To_node_NodeReference(in, out, s)
}

func autoConvert_node_NodeReference_To_v1beta1_NodeReference(in *node.NodeReference, out *NodeReference, s conversion.Scope) error {
	out.Name = in.Name
	out.OSImage = in.OSImage
	out.Architecture = in.Architecture
	out.KubeletVersion = in.KubeletVersion
	out.RuntimeVersion = in.RuntimeVersion
	return nil
}

// Convert_node_NodeReference_To_v1beta1_NodeReference is an autogenerated conversion function.
func Convert_node_NodeReference_To_v1beta1_NodeReference(in *node.NodeReference, out *NodeReference, s conversion.Scope) error {
	return autoConvert_node_NodeReference_To_v1beta1_NodeReference(in, out, s)
}

func autoConvert_v1beta1_ObjectMeta_To_node_ObjectMeta(in *ObjectMeta, out *node.ObjectMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.GenerateName = in.GenerateName
	out.Namespace = in.Namespace
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.OwnerReferences = *(*[]v1.OwnerReference)(unsafe.Pointer(&in.OwnerReferences))
	return nil
}

// Convert_v1beta1_ObjectMeta_To_node_ObjectMeta is an autogenerated conversion function.
func Convert_v1beta1_ObjectMeta_To_node_ObjectMeta(in *ObjectMeta, out *node.ObjectMeta, s conversion.Scope) error {
	return autoConvert_v1beta1_ObjectMeta_To_node_ObjectMeta(in, out, s)
}

func autoConvert_node_ObjectMeta_To_v1beta1_ObjectMeta(in *node.ObjectMeta, out *ObjectMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.GenerateName = in.GenerateName
	out.Namespace = in.Namespace
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.OwnerReferences = *(*[]v1.OwnerReference)(unsafe.Pointer(&in.OwnerReferences))
	return nil
}

// Convert_node_ObjectMeta_To_v1beta1_ObjectMeta is an autogenerated conversion function.
func Convert_node_ObjectMeta_To_v1beta1_ObjectMeta(in *node.ObjectMeta, out *ObjectMeta, s conversion.Scope) error {
	return autoConvert_node_ObjectMeta_To_v1beta1_ObjectMeta(in, out, s)
}

func autoConvert_v1beta1_ProviderSpec_To_node_ProviderSpec(in *ProviderSpec, out *node.ProviderSpec, s conversion.Scope) error {
	out.Type = node.MachineType(in.Type)
	out.Value = (*runtime.RawExtension)(unsafe.Pointer(in.Value))
	return nil
}

// Convert_v1beta1_ProviderSpec_To_node_ProviderSpec is an autogenerated conversion function.
func Convert_v1beta1_ProviderSpec_To_node_ProviderSpec(in *ProviderSpec, out *node.ProviderSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ProviderSpec_To_node_ProviderSpec(in, out, s)
}

func autoConvert_node_ProviderSpec_To_v1beta1_ProviderSpec(in *node.ProviderSpec, out *ProviderSpec, s conversion.Scope) error {
	out.Type = MachineType(in.Type)
	out.Value = (*runtime.RawExtension)(unsafe.Pointer(in.Value))
	return nil
}

// Convert_node_ProviderSpec_To_v1beta1_ProviderSpec is an autogenerated conversion function.
func Convert_node_ProviderSpec_To_v1beta1_ProviderSpec(in *node.ProviderSpec, out *ProviderSpec, s conversion.Scope) error {
	return autoConvert_node_ProviderSpec_To_v1beta1_ProviderSpec(in, out, s)
}

func autoConvert_v1beta1_RollingUpgrade_To_node_RollingUpgrade(in *RollingUpgrade, out *node.RollingUpgrade, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RollingUpgradeSpec_To_node_RollingUpgradeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RollingUpgradeStatus_To_node_RollingUpgradeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RollingUpgrade_To_node_RollingUpgrade is an autogenerated conversion function.
func Convert_v1beta1_RollingUpgrade_To_node_RollingUpgrade(in *RollingUpgrade, out *node.RollingUpgrade, s conversion.Scope) error {
	return autoConvert_v1beta1_RollingUpgrade_To_node_RollingUpgrade(in, out, s)
}

func autoConvert_node_RollingUpgrade_To_v1beta1_RollingUpgrade(in *node.RollingUpgrade, out *RollingUpgrade, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_RollingUpgradeSpec_To_v1beta1_RollingUpgradeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_RollingUpgradeStatus_To_v1beta1_RollingUpgradeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_RollingUpgrade_To_v1beta1_RollingUpgrade is an autogenerated conversion function.
func Convert_node_RollingUpgrade_To_v1beta1_RollingUpgrade(in *node.RollingUpgrade, out *RollingUpgrade, s conversion.Scope) error {
	return autoConvert_node_RollingUpgrade_To_v1beta1_RollingUpgrade(in, out, s)
}

func autoConvert_v1beta1_RollingUpgradeCondition_To_node_RollingUpgradeCondition(in *RollingUpgradeCondition, out *node.RollingUpgradeCondition, s conversion.Scope) error {
	out.Type = node.UpgradeConditionType(in.Type)
	out.Status = core.ConditionStatus(in.Status)
	return nil
}

// Convert_v1beta1_RollingUpgradeCondition_To_node_RollingUpgradeCondition is an autogenerated conversion function.
func Convert_v1beta1_RollingUpgradeCondition_To_node_RollingUpgradeCondition(in *RollingUpgradeCondition, out *node.RollingUpgradeCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_RollingUpgradeCondition_To_node_RollingUpgradeCondition(in, out, s)
}

func autoConvert_node_RollingUpgradeCondition_To_v1beta1_RollingUpgradeCondition(in *node.RollingUpgradeCondition, out *RollingUpgradeCondition, s conversion.Scope) error {
	out.Type = UpgradeConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	return nil
}

// Convert_node_RollingUpgradeCondition_To_v1beta1_RollingUpgradeCondition is an autogenerated conversion function.
func Convert_node_RollingUpgradeCondition_To_v1beta1_RollingUpgradeCondition(in *node.RollingUpgradeCondition, out *RollingUpgradeCondition, s conversion.Scope) error {
	return autoConvert_node_RollingUpgradeCondition_To_v1beta1_RollingUpgradeCondition(in, out, s)
}

func autoConvert_v1beta1_RollingUpgradeList_To_node_RollingUpgradeList(in *RollingUpgradeList, out *node.RollingUpgradeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.RollingUpgrade)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_RollingUpgradeList_To_node_RollingUpgradeList is an autogenerated conversion function.
func Convert_v1beta1_RollingUpgradeList_To_node_RollingUpgradeList(in *RollingUpgradeList, out *node.RollingUpgradeList, s conversion.Scope) error {
	return autoConvert_v1beta1_RollingUpgradeList_To_node_RollingUpgradeList(in, out, s)
}

func autoConvert_node_RollingUpgradeList_To_v1beta1_RollingUpgradeList(in *node.RollingUpgradeList, out *RollingUpgradeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RollingUpgrade)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_RollingUpgradeList_To_v1beta1_RollingUpgradeList is an autogenerated conversion function.
func Convert_node_RollingUpgradeList_To_v1beta1_RollingUpgradeList(in *node.RollingUpgradeList, out *RollingUpgradeList, s conversion.Scope) error {
	return autoConvert_node_RollingUpgradeList_To_v1beta1_RollingUpgradeList(in, out, s)
}

func autoConvert_v1beta1_RollingUpgradeSpec_To_node_RollingUpgradeSpec(in *RollingUpgradeSpec, out *node.RollingUpgradeSpec, s conversion.Scope) error {
	out.MachineSetName = in.MachineSetName
	out.AutoUpgrade = (*bool)(unsafe.Pointer(in.AutoUpgrade))
	if err := Convert_v1beta1_AutoUpgradeOptions_To_node_AutoUpgradeOptions(&in.UpgradeOptions, &out.UpgradeOptions, s); err != nil {
		return err
	}
	out.Components = *(*[]node.ComponentType)(unsafe.Pointer(&in.Components))
	if err := Convert_v1beta1_UpdateStrategy_To_node_UpdateStrategy(&in.Strategy, &out.Strategy, s); err != nil {
		return err
	}
	out.DesiredKubeletVersion = in.DesiredKubeletVersion
	out.DesiredRuntimeVersion = in.DesiredRuntimeVersion
	out.IgnoreUpgradeFailures = (*bool)(unsafe.Pointer(in.IgnoreUpgradeFailures))
	return nil
}

// Convert_v1beta1_RollingUpgradeSpec_To_node_RollingUpgradeSpec is an autogenerated conversion function.
func Convert_v1beta1_RollingUpgradeSpec_To_node_RollingUpgradeSpec(in *RollingUpgradeSpec, out *node.RollingUpgradeSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RollingUpgradeSpec_To_node_RollingUpgradeSpec(in, out, s)
}

func autoConvert_node_RollingUpgradeSpec_To_v1beta1_RollingUpgradeSpec(in *node.RollingUpgradeSpec, out *RollingUpgradeSpec, s conversion.Scope) error {
	out.MachineSetName = in.MachineSetName
	out.AutoUpgrade = (*bool)(unsafe.Pointer(in.AutoUpgrade))
	if err := Convert_node_AutoUpgradeOptions_To_v1beta1_AutoUpgradeOptions(&in.UpgradeOptions, &out.UpgradeOptions, s); err != nil {
		return err
	}
	out.Components = *(*[]ComponentType)(unsafe.Pointer(&in.Components))
	if err := Convert_node_UpdateStrategy_To_v1beta1_UpdateStrategy(&in.Strategy, &out.Strategy, s); err != nil {
		return err
	}
	out.DesiredKubeletVersion = in.DesiredKubeletVersion
	out.DesiredRuntimeVersion = in.DesiredRuntimeVersion
	out.IgnoreUpgradeFailures = (*bool)(unsafe.Pointer(in.IgnoreUpgradeFailures))
	return nil
}

// Convert_node_RollingUpgradeSpec_To_v1beta1_RollingUpgradeSpec is an autogenerated conversion function.
func Convert_node_RollingUpgradeSpec_To_v1beta1_RollingUpgradeSpec(in *node.RollingUpgradeSpec, out *RollingUpgradeSpec, s conversion.Scope) error {
	return autoConvert_node_RollingUpgradeSpec_To_v1beta1_RollingUpgradeSpec(in, out, s)
}

func autoConvert_v1beta1_RollingUpgradeStatus_To_node_RollingUpgradeStatus(in *RollingUpgradeStatus, out *node.RollingUpgradeStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.CompletePercentage = in.CompletePercentage
	out.StartTime = in.StartTime
	out.EndTime = in.EndTime
	out.MachinesProcessed = in.MachinesProcessed
	out.TotalMachines = in.TotalMachines
	out.TotalProcessingTime = in.TotalProcessingTime
	out.Conditions = *(*[]node.RollingUpgradeCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_RollingUpgradeStatus_To_node_RollingUpgradeStatus is an autogenerated conversion function.
func Convert_v1beta1_RollingUpgradeStatus_To_node_RollingUpgradeStatus(in *RollingUpgradeStatus, out *node.RollingUpgradeStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RollingUpgradeStatus_To_node_RollingUpgradeStatus(in, out, s)
}

func autoConvert_node_RollingUpgradeStatus_To_v1beta1_RollingUpgradeStatus(in *node.RollingUpgradeStatus, out *RollingUpgradeStatus, s conversion.Scope) error {
	out.Phase = in.Phase
	out.CompletePercentage = in.CompletePercentage
	out.StartTime = in.StartTime
	out.EndTime = in.EndTime
	out.MachinesProcessed = in.MachinesProcessed
	out.TotalMachines = in.TotalMachines
	out.TotalProcessingTime = in.TotalProcessingTime
	out.Conditions = *(*[]RollingUpgradeCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_node_RollingUpgradeStatus_To_v1beta1_RollingUpgradeStatus is an autogenerated conversion function.
func Convert_node_RollingUpgradeStatus_To_v1beta1_RollingUpgradeStatus(in *node.RollingUpgradeStatus, out *RollingUpgradeStatus, s conversion.Scope) error {
	return autoConvert_node_RollingUpgradeStatus_To_v1beta1_RollingUpgradeStatus(in, out, s)
}

func autoConvert_v1beta1_TagSpecification_To_node_TagSpecification(in *TagSpecification, out *node.TagSpecification, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_v1beta1_TagSpecification_To_node_TagSpecification is an autogenerated conversion function.
func Convert_v1beta1_TagSpecification_To_node_TagSpecification(in *TagSpecification, out *node.TagSpecification, s conversion.Scope) error {
	return autoConvert_v1beta1_TagSpecification_To_node_TagSpecification(in, out, s)
}

func autoConvert_node_TagSpecification_To_v1beta1_TagSpecification(in *node.TagSpecification, out *TagSpecification, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_node_TagSpecification_To_v1beta1_TagSpecification is an autogenerated conversion function.
func Convert_node_TagSpecification_To_v1beta1_TagSpecification(in *node.TagSpecification, out *TagSpecification, s conversion.Scope) error {
	return autoConvert_node_TagSpecification_To_v1beta1_TagSpecification(in, out, s)
}

func autoConvert_v1beta1_UpdateStrategy_To_node_UpdateStrategy(in *UpdateStrategy, out *node.UpdateStrategy, s conversion.Scope) error {
	out.Type = node.UpdateStrategyType(in.Type)
	out.MaxUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnavailable))
	out.UpgradeTimeout = (*v1.Duration)(unsafe.Pointer(in.UpgradeTimeout))
	return nil
}

// Convert_v1beta1_UpdateStrategy_To_node_UpdateStrategy is an autogenerated conversion function.
func Convert_v1beta1_UpdateStrategy_To_node_UpdateStrategy(in *UpdateStrategy, out *node.UpdateStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_UpdateStrategy_To_node_UpdateStrategy(in, out, s)
}

func autoConvert_node_UpdateStrategy_To_v1beta1_UpdateStrategy(in *node.UpdateStrategy, out *UpdateStrategy, s conversion.Scope) error {
	out.Type = UpdateStrategyType(in.Type)
	out.MaxUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnavailable))
	out.UpgradeTimeout = (*v1.Duration)(unsafe.Pointer(in.UpgradeTimeout))
	return nil
}

// Convert_node_UpdateStrategy_To_v1beta1_UpdateStrategy is an autogenerated conversion function.
func Convert_node_UpdateStrategy_To_v1beta1_UpdateStrategy(in *node.UpdateStrategy, out *UpdateStrategy, s conversion.Scope) error {
	return autoConvert_node_UpdateStrategy_To_v1beta1_UpdateStrategy(in, out, s)
}
