apiVersion: v2
name: karpenter
description: A Helm chart for TKE Karpenter provider.
type: application
version: 0.2.0-beta1
appVersion: 0.2.0-beta1
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle